name: Release 

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno 1.16.1
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.16.1
      - name: Reload
        run: make reload 
      - name: Compile
        run: make compile_all 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
